name: 'Run App DylanMostek'

on: [push, pull_request]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libssl1.1
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1 || sudo apt-get install -y libssl1.1=1.1.1f-1ubuntu2.16

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.301'

      - name: Restore packages
        run: dotnet restore GithubActions.sln

      - name: Build
        run: msbuild /p:Configuration=Release GithubActions.sln
